version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    ports:
      - "9090:9090"
    networks:
      - kafka-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - kafka-net

  kafka-exporter:
    image: danielqsj/kafka-exporter:1.4.1
    container_name: kafka-exporter
    environment:
      KAFKA_URI: "kafka1:9092,kafka2:9093,kafka3:9094"
      SCRAPE_TIMEOUT: "10s"
    ports:
      - "9308:9308"
    networks:
      - kafka-net
    depends_on:
      - kafka1
      - kafka2
      - kafka3

networks:
  kafka-net:
    external: true
